sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - lerna run clean
  - lerna bootstrap
script:
  - lerna run build
after_success:
  - lerna run semantic-release
branches:
  only:
    - master