sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn build
after_success:
  - yarn semantic-release
branches:
  only:
    - master